= Critter

Critter will look at your source code and generate type safe criteria builders for each model object.  It will also, by default,
generate codecs specific to your entities removing the need for most reflections at run time.

== What difference does it make?

Before critter, your criteria might look something like this:

[source,java]
----
Query<Book> query = ds.find(Book.class)
    .filter(and(
        eq("bookmark", bookmark),
        eq("database", database)));
----

But using critter, it would look like this:

[source,java]
----
Query<Book> query = ds.find(Book.class)
    .filter(and(
        Book.bookmark().eq(bookmark),
        Book.database().eq(database)));
----

Notice how bookmark() and database() methods were created based on the model object Book's fields.  The comparison
methods you're familiar with from Morphia's filters API are all there but now only take the type of the field itself.
With this code in place if the model object changes, the code above runs the risk of failing to compile allowing you to
catch model/query conflicts at compile time rather than waiting for things to fail at runtime (or in your tests if you're
lucky enough to have those).

You can see working examples in the [tests](https://github.com/MorphiaOrg/critter/tree/master/tests).

== Build Tools

Critter supports a number of configuration options that can be passed to the maven or gradle plugins depending on your build.

[options="header"]
|=======
| Option | Property | Description
| criteriaPackage | critter.package | If this option is omitted, the code will be generated using the
package of your entities with `.criteria` appended.  If a value is given, every criteria generated will live in the
named package.
| force | critter.force | This defaults to false but if it's set to true, critter will always regenerate your criteria classes.
| format | critter.format | Turns code formatting on or off.  Possible values: true, false. Defaults to true.
| generateCodecs | critter.codecs | Turns codec generation on or off.  Possible values: true, false. Defaults to true.
| outputType | critter.type | Setting this changes the language used in the generated criteria classes.
Possible values: java, kotlin
|=======

To use it, you simply need to add a plugin to your build file.  To use critter with maven, you would update your pom as shown here:

[source,xml,subs="verbatim,attributes"]
----
<plugin>
    <groupId>dev.morphia.critter</groupId>
    <artifactId>critter-maven</artifactId>
    <version>{version}</version>
    <executions>
        <execution>
            <id>critter</id>
            <goals>
                <goal>generate</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <criteriaPackage>com.bob.bar</criteriaPackage>
    </configuration>
</plugin>
----
This will generate your criteria classes in `target/generated-sources/critter` and add the directory as a source directory of
your maven project.

If you use gradle, you would configure your file like so (using the kotlin dsl):

[source,kotlin,subs="verbatim,attributes"]
----
plugins {
    id("dev.morphia.critter") version "{version}"
}


tasks {
    critter {
        force = true
        outputType = "java"
    }
}
----
This will generate your criteria classes in `build/generated-src/critter` and add the directory as a source directory of your gradle
project.

== IDEA Users

IDEA users will need to enable the plugin registry in the maven configuration options for IDEA to pick up the plugin.

== Issues and support

Please check xref:issues-help.adoc[here] if you find an issue or need help.
