name: Build Project

on: [ push, workflow_dispatch ]

jobs:
  critter:
    uses: evanchooly/workflows/.github/workflows/build-project.yml@master

  Snapshots:
    if: ${{ github.repository == 'MorphiaOrg/critter' && github.ref == 'refs/heads/master' }}
    needs:
      - critter
    uses: evanchooly/workflows/.github/workflows/snapshot.yml@master
