name: Build Project

on: [ push, workflow_dispatch ]

jobs:
  critter:
    uses: evanchooly/workflows/.github/workflows/build-project.yml@master

  Snapshots:
    if: ${{ github.repository == 'MorphiaOrg/critter' && github.ref == 'refs/heads/master' }}
    needs:
      - critter
    uses: evanchooly/workflows/.github/workflows/snapshots.yml@master
    secrets:
      MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      MAVEN_CENTRAL_TOKEN: ${{ secrets.SONATYPE_PASSWORD }}
      MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}