name: Dependabot PRs

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  Build:
    uses: evanchooly/workflows/.github/workflows/build.yml@master
  dependabot:
    needs:
      - Build
    uses: evanchooly/workflows/.github/workflows/pull-request.yml@master